version: 'version'

services:
  mfb-container:
    image: 13angs/mfb-container:latest
    build: 
      context: ../../../../container
      dockerfile: Dockerfile
    ports:
      - "4001:80"
    networks:
      - mfb-network

networks:
  mfb-network:
    name: mfb-network
    external: true