version: 'version'

services:
  mfb-checkout:
    image: 13angs/mfb-checkout:latest
    build: 
      context: ../../../
      dockerfile: ./packages/checkout/Dockerfile
      args:
        - "CHECKOUT_HOST=${CHECKOUT_HOST}"
    container_name: msb-checkout
    ports:
      - target: 80
        published: ${CHECKOUT_HOST_PORT}
    networks:
      - mfb-network

networks:
  mfb-network:
    name: mfb-network
    external: true